---

- name: Remove unneeded packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ remove_packages }}"

- name: Install packages required by Oracle on EL7
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ install_packages }}"

# Enable SELinux
- selinux:
    policy: targeted
    state: enforcing

# swap space
# Create machine with some free disk space
# swapon -s
# free -m
# df -h
# /etc/fstab

# Enable disk UUID in *.vmx and set -g in /etc/scsi_id.config

- name: Oracle-recommended PAM config
  lineinfile:
    path: /etc/pam.d/login
    state: present
    line: "session    required     pam_limits.so"
  tags:
    - pamconfig

- name: Oracle-recommended security limits
  template:
    src: 99-grid-oracle-limits.conf.j2
    dest: /etc/security/limits.d/99-grid-oracle-limits.conf
    backup: true
  tags:
    - seclimit

- name: Add the required oracle kernel changes to a file in /etc/sysctl.d
  template:
    src: 98-oracle-kernel.conf.j2
    dest: /etc/sysctl.d/98-oracle-sysctl.conf
    mode: '0644'

- name: User | Add group(s)
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ oracle_groups }}"
  tags:
   - group

- name: User | Add Oracle user
  user:
    name: "{{ item.username }}"
    group: "{{ item.primgroup }}"
    groups: "{{ item.othergroups }}"
    uid: "{{ item.uid }}"
    generate_ssh_key: true
    append: true
    state: present
    comment: "{{ item.comment }}"
  with_items: "{{oracle_users}}"

- name: User | Add Grid user
  user:
    name: "{{ item.username }}"
    group: "{{ item.primgroup }}"
    groups: "{{ item.othergroups }}"
    uid: "{{ item.uid }}"
    generate_ssh_key: true
    append: true
    state: present
    comment: "{{ item.comment }}"
  when: role_separation
  with_items: "{{grid_users}}"

- name: User | Add Oracle user to sudoers.j2
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ item.username }}
    owner: root
    mode: 0600
  with_items: "{{oracle_users}}"

- name: User | Add Grid user to sudoers.j2
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ item.username }}
    owner: root
    mode: 0600
  with_items: "{{grid_users}}"
  when: role_separation

- name: Oracle hugepages
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items: "{{oracle_hugepages}}"

- name: Set the ulimit script in /etc/profile.d
  template:
    src: 99-oracle-grid.sh.j2
    dest: /etc/profile.d/99-oracle-grid.sh
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: Set the .aliases
  template:
    src: aliases.j2
    dest: "/home/{{ item }}/.aliases"
    owner: "{{ item }}"
    group: oinstall
    mode: "u=rw,g=r,o=r"
  with_items:
    - oracle
    - grid

- name: Set the .bashrc
  template:
    src: bashrc.j2
    dest: "/home/{{ item }}/.bashrc"
    owner: "{{ item }}"
    group: oinstall
    mode: "u=rw,g=r,o=r"
  with_items:
    - oracle
    - grid

- name: Set the .bash_profile
  template:
    src: bash_profile.j2
    dest: "/home/{{ item }}/.bash_profile"
    owner: "{{ item }}"
    group: oinstall
    mode: "u=rw,g=r,o=r"
  with_items:
    - oracle
    - grid

- name: Customize the tuned-profiles-oracle profile
  lineinfile:
    path: /usr/lib/tuned/oracle/tuned.conf
    state: absent
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ tuned }}"

- name: Enable tuned service
  service:
    name: tuned
    enabled: yes
    state: started

#- name: Switch tuned profile to oracle
#  shell: tuned-adm profile oracle

# Docker doesn't have grub?
# Better to do in kickstart
# name: Disable Transparent Huge Pages in grub
# lineinfile:
#   path: /etc/default/grub
#   state: present
#   regexp: '(^\s*kernel(\s+(?!transparent_hugepage=never)[\w=/\-\.\,]+)*)\s*$'
#   line: '\1 transparent_hugepage=never'
#   backrefs: yes
# notify: Run update-grub